l_english:

 CUSTOM_DIFFICULTY_GROUP_NAME:0 "AI Buffs"
 diff_strong_ai_generic:0 "Stronger AI"
 custom_diff_strong_ger:0 "Strengthen Germany"
 custom_diff_strong_ita:0 "Strengthen Italy"
 custom_diff_strong_sov:0 "Strengthen Russia"
 custom_diff_strong_fra:0 "Strengthen France"
 custom_diff_strong_eng:0 "Strengthen United Kingdom"
 custom_diff_strong_usa:0 "Strengthen USA"
 custom_diff_strong_jap:0 "Strengthen Japan"
 custom_diff_strong_chi:0 "Strengthen China"
 custom_diff_strong_rus:0 "Strengthen Russia"